import { createEmptyRecord } from './dataModel.js';

function buildSample(overrides) {
  return { ...createEmptyRecord(), ...overrides };
}

export const sampleRecords = [
  buildSample({
    sourceType: 'manual',
    consultationDate: '2026-01-15',
    consultantName: '田中相談員',
    clientName: '山田花子',
    companyName: '和み食堂',
    industry: '飲食',
    productFeatures: '地元食材を使った定食ランチ',
    valueProposition: '手頃な価格で健康的な食事',
    targetCustomer: '近隣オフィスワーカー',
    businessModel: '店内飲食 + テイクアウト',
    strengths: '調理が速い、固定客が多い',
    consultationDetails: 'ランチ客は多いが夜の売上が落ち込んでいる。',
    currentIssues: '夜営業の集客不足、SNS更新が停滞。',
    desiredDirection: '夜の売上比率を上げたい。',
    consultationType: '集客',
    proposalSummary: '夜限定メニューとInstagram訴求。',
    nextActions: '夜メニュー試作、投稿計画作成。',
    notes: '近隣企業への法人弁当提案余地あり。',
    summary: {
      overview: '昼は好調、夜の稼働率改善が主題。',
      keyIssues: '集客と告知導線。',
      proposalPoints: '夜限定定食、SNS運用、法人販路。',
      nextCheckpoints: '1か月後に夜客数と投稿頻度を確認。',
    },
    tags: {
      industryTags: ['飲食'],
      issueTags: ['集客', 'SNS'],
      actionTags: ['Instagram', 'イベント'],
      resultTags: ['客数増'],
    },
    aiOutput: {
      situationSummary: '昼需要が強い一方で夜の認知不足が課題。',
      issueAnalysis: '夜の来店動機設計と告知チャネルが弱い。',
      topPriorities: ['夜メニュー差別化', '週3回SNS投稿', '法人向け提案'],
      quickActions: ['夜限定セットを2週間試験導入', '投稿テンプレート作成'],
      midTermStrategies: ['法人弁当を定期契約化', '顧客アンケート設計'],
      differentiationIdeas: ['地元農家コラボ定食'],
      copyIdeas: ['仕事帰りに、ほっと一膳。'],
      homework: ['夜来店理由の仮説を3つ整理'],
      consultationSummary: '夜集客を軸に短中期施策を設計。',
    },
  }),
  buildSample({
    sourceType: 'imported',
    consultationDate: '2026-02-08',
    clientName: '佐藤健一',
    companyName: 'まちの雑貨店MORI',
    industry: '小売',
    consultationDetails: '来店数減少と客単価低下。',
    currentIssues: '価格競争で粗利悪化。',
    desiredDirection: 'リピート顧客を増やしたい。',
    consultationType: 'リピート対策',
    productFeatures: '生活雑貨・ギフト用品',
    valueProposition: '地域密着の提案接客',
    targetCustomer: '30〜50代のファミリー層',
    businessModel: '店舗販売中心',
    strengths: 'ギフト提案力',
    rawText: '議事録取り込みデータ',
    summary: {
      overview: '客数減をリピート施策で補う方針。',
      keyIssues: '販路開拓と価格設定。',
      proposalPoints: 'LINE会員施策、ギフト提案強化。',
      nextCheckpoints: '会員化率を次回確認。',
    },
    tags: {
      industryTags: ['小売'],
      issueTags: ['リピート', '価格設定'],
      actionTags: ['導線改善', 'ターゲット再設定'],
      resultTags: [],
    },
  }),
  buildSample({
    sourceType: 'manual',
    consultationDate: '2026-02-20',
    clientName: '高橋工業',
    companyName: '高橋工業株式会社',
    industry: '製造業',
    consultationDetails: '新規受注が停滞し、既存依存が高い。',
    currentIssues: '営業体制が属人的。',
    desiredDirection: 'BtoB販路を増やしたい。',
    consultationType: '販路開拓',
    productFeatures: '精密板金加工',
    valueProposition: '短納期・小ロット対応',
    targetCustomer: '中小機械メーカー',
    businessModel: '受託製造',
    strengths: '品質安定・短納期',
    tags: {
      industryTags: ['製造業'],
      issueTags: ['販路開拓', '営業'],
      actionTags: ['BtoB提案', 'LP'],
      resultTags: [],
    },
  }),
  buildSample({
    sourceType: 'imported',
    consultationDate: '2026-03-02',
    clientName: '鈴木愛',
    companyName: 'ケアサポート青空',
    industry: 'サービス業',
    consultationDetails: '問い合わせはあるが契約化率が低い。',
    currentIssues: '提案内容の差別化が伝わっていない。',
    desiredDirection: '高単価プラン比率を上げたい。',
    consultationType: 'ブランディング',
    productFeatures: '訪問型生活支援サービス',
    valueProposition: '柔軟なプラン設計',
    targetCustomer: '高齢者世帯と家族',
    businessModel: '月額契約',
    strengths: 'スタッフ対応品質',
    tags: {
      industryTags: ['サービス業'],
      issueTags: ['ブランディング', '価格設定'],
      actionTags: ['商品改善', '値上げ訴求'],
      resultTags: [],
    },
  }),
];
